@foreach($result as $section)
    <h4>{{$section->name}}</h4>
    <table>
        <tr>
            <td>No</td>
            <td>PPDS</td>
            <td>Pembimbing</td>
            <td>Tanggal</td>
            @if(isset($section->parse_desc))
                @if(isset($section->parse_desc['field_1']))
                    <td>
                        {{$section->parse_desc['field_1']}}
                    </td>
                @endif
                @if(isset($section->parse_desc['field_2']))
                    <td>
                        {{$section->parse_desc['field_2']}}
                    </td>
                @endif
                @if(isset($section->parse_desc['field_3']))
                    <td>
                        {{$section->parse_desc['field_3']}}
                    </td>
                @endif
                @if(isset($section->parse_desc['field_4']))
                    <td>
                        {{$section->parse_desc['field_4']}}
                    </td>
                @endif
                @if(isset($section->parse_desc['field_5']))
                    <td>
                        {{$section->parse_desc['field_5']}}
                    </td>
                @endif
                @if(isset($section->parse_desc['field_6']))
                    <td>
                        {{$section->parse_desc['field_6']}}
                    </td>
                @endif
            @endif
        </tr>
        @foreach($section->logbook as $logbook)
            <tr>
                <td>{{$loop->iteration}}</td>
                <td>
                    @if(isset($logbook->student))
                        {{$logbook->student['name']}}
                    @endif
                </td>
                <td>
                    @if(isset($logbook->lecture))
                        {{$logbook->lecture['name']}}
                    @endif
                </td>
                <td>{{$logbook->date}}</td>
                @if(isset($section->parse_desc['field_1']))
                    <td>
                        {{$logbook->field_1}}
                    </td>
                @endif
                @if(isset($section->parse_desc['field_2']))
                    <td>
                        {{$logbook->field_2}}
                    </td>
                @endif
                @if(isset($section->parse_desc['field_3']))
                    <td>
                        {{$logbook->field_3}}
                    </td>
                @endif
                @if(isset($section->parse_desc['field_4']))
                    <td>
                        {{$logbook->field_4}}
                    </td>
                @endif
                @if(isset($section->parse_desc['field_5']))
                    <td>
                        {{$logbook->field_5}}
                    </td>
                @endif
                @if(isset($section->parse_desc['field_6']))
                    <td>
                        {{$logbook->field_6}}
                    </td>
                @endif
            </tr>
        @endforeach
    </table>
@endforeach
